export const HELLOWORLD = "HELLOWORLD"

/**
 * GET DEVICE TOKEN
 */

 export const FETCH_TOKEN_START = "FETCH_TOKEN"
 export const FETCH_TOKEN_ERROR = "FETCH_TOKEN_ERROR"
 export const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS"
 export const FETCH_TOKEN_FAIL = "FETCH_TOKEN_FAIL"
 export const FETCH_TOKEN_STOP = "FETCH_TOKEN_STOP"
 export const SEND_TOKEN_TO_SERVER_START = "SEND_TOKEN_TO_SERVER_START"
 export const SEND_TOKEN_TO_SERVER_ERROR = "SEND_TOKEN_TO_SERVER_ERROR"
 export const SEND_TOKEN_TO_SERVER_SUCCESS = "SEND_TOKEN_TO_SERVER_SUCCESS"
 export const SEND_TOKEN_TO_SERVER_FAIL = "SEND_TOKEN_TO_SERVER_FAIL"
 export const SEND_TOKEN_TO_SERVER_STOP = "SEND_TOKEN_TO_SERVER_STOP"
 /**
  * AUTHENTICATION
  *  */



  /**
   * LOAD DATA
   */


   /**
    * CONFIGURATIONS
    */



    /**
     * UI STATE
     */